[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
SITE_NAME = "Sistema de Rifas Online"
RAILWAY_ENVIRONMENT = "production" 